# -*- coding: utf-8 -*-
"""Forward_Propagation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QYUw5GzQr5vGoA8x-QmLkOYXwexMgUOK
"""

import numpy as np
input_data=np.array([2,3])
weights={'node_0':np.array([1,1]),
         'node_1':np.array([-1,1]),
         'op':np.array([2,-1])}
node_0_value=(input_data*weights['node_0']).sum()
node_1_value=(input_data*weights['node_1']).sum()
hidden_layer_values=np.array([node_0_value,node_1_value])
print(hidden_layer_values)

output=(hidden_layer_values*weights['op']).sum()
print(output)